default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: iwsyhgia
  username: iwsyhgia
  password: 12345678

production:
  <<: *default
  database: database_name
  username: your_username
  password: your_password
